name: Waka Readme

on:
  schedule:
    # Runs at 12am UTC (every day at midnight UTC)
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    name: Update this repo's README with WakaTime Stats
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          # Optional: You can add more options here (e.g., show_total_commit: true)